print(". 　　　。　　　　•　 　ﾟ　　。 　　.")
print("　　　.　　　 　　.　　　　　。　　 。　.")
print(".　　 。　　　　　 ඞ 。 . 　　 • 　　　　•")
print("　　ﾟ　　 Python was not An Impostor.　 。　.")
print("　　'　　　 1 Impostor remains 　 　　。")
print("　　ﾟ　　　.　　　. ,　　　　.　 .")